services:
  frontend-service:
    build:
      args:
        user: admin
        uid: 1000
      context: ./frontend-service
      dockerfile: Dockerfile
    container_name: frontend-service
    restart: unless-stopped
    working_dir: /var/www/frontend
    volumes:
      - ./frontend-service:/var/www/frontend
    networks:
      - laravel-app
    expose:
      - 9000

  kitchen-service:
    build:
      args:
        user: admin2
        uid: 1001
      context: ./kitchen-service
      dockerfile: Dockerfile
    container_name: kitchen-service
    restart: unless-stopped
    working_dir: /var/www/kitchen
    volumes:
      - ./kitchen-service:/var/www/kitchen
    networks:
      - laravel-app
    expose:
      - 9000

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      #MYSQL_PASSWORD: ${DB_PASSWORD}
      #MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - laravel-app

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - ./frontend-service:/var/www/frontend
      - ./kitchen-service:/var/www/kitchen
      - /etc/letsencrypt/live/dariocapdevila.com.ar:/etc/letsencrypt/live/dariocapdevila.com.ar
      - /etc/letsencrypt/archive/dariocapdevila.com.ar:/etc/letsencrypt/archive/dariocapdevila.com.ar
    depends_on:
      - frontend-service
      - kitchen-service
    networks:
      - laravel-app

networks:
  laravel-app:
    driver: bridge